server:
  port: 8086

spring:
  kafka:
    consumer:
      group-id: group-id-new
    bootstrap-servers: localhost:29092

schema:
  registry:
    url: http://localhost:8081

messaging:
  topic:
    order: topic-order-new